-- MySQL Script generated by MySQL Workbench
-- Sat Oct  8 19:04:13 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kanban
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kanban
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kanban` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `kanban` ;

-- -----------------------------------------------------
-- Table `kanban`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanban`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanban`.`Board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanban`.`Board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `ownerId` INT NOT NULL,
  `public` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `board_name` (`name` ASC),
  INDEX `board_user` (`ownerId` ASC),
  CONSTRAINT `board_owner`
    FOREIGN KEY (`ownerId`)
    REFERENCES `kanban`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanban`.`Lane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanban`.`Lane` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `authorId` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `displayorder` INT NOT NULL DEFAULT 1,
  `boardId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `lane_name` (`title` ASC),
  INDEX `authorId_idx` (`authorId` ASC),
  INDEX `boardId_idx` (`boardId` ASC),
  CONSTRAINT `lane_author`
    FOREIGN KEY (`authorId`)
    REFERENCES `kanban`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lane_board`
    FOREIGN KEY (`boardId`)
    REFERENCES `kanban`.`Board` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanban`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanban`.`Card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `authorId` INT NOT NULL,
  `displayOrder` INT NOT NULL DEFAULT 1,
  `title` VARCHAR(500) NOT NULL,
  `description` TEXT(5000) NULL,
  `laneId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `title` (`title` ASC),
  INDEX `lane_displayOrder` (`displayOrder` ASC, `laneId` ASC),
  INDEX `author_idx` (`authorId` ASC),
  INDEX `lane_idx` (`laneId` ASC),
  CONSTRAINT `card_author`
    FOREIGN KEY (`authorId`)
    REFERENCES `kanban`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `card_lane`
    FOREIGN KEY (`laneId`)
    REFERENCES `kanban`.`Lane` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanban`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanban`.`Comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commentText` TEXT(5000) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `editedAt` DATETIME NOT NULL,
  `authorId` INT,
  `cardId` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `comment_card`
    FOREIGN KEY (`cardId`)
    REFERENCES `kanban`.`Card` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_author`
    FOREIGN KEY (`authorId`)
    REFERENCES `kanban`.`User` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanban`.`BoardMember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanban`.`BoardMember` (
  `boardId` INT NOT NULL,
  `userId` INT NOT NULL,
  `isAdmin` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`boardId`, `userId`),
  INDEX `userId_idx` (`userId` ASC),
  CONSTRAINT `user`
    FOREIGN KEY (`userId`)
    REFERENCES `kanban`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `board`
    FOREIGN KEY (`boardId`)
    REFERENCES `kanban`.`Board` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
